// Generated by FlutterFire CLI, do not edit manually.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxzaK1NhRqVFq1E83oskMIusdbBjI7zLs',
    appId: '1:382810899464:android:f552cf93b7f6bebab33dbd',
    messagingSenderId: '382810899464',
    projectId: 'shizuka-94a02',
    storageBucket: 'shizuka-94a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASH-jHm89ooijw63sRyVKi13tL0JRwSa8',
    appId: '1:382810899464:ios:a1687ed874f48cf0b33dbd',
    messagingSenderId: '382810899464',
    projectId: 'shizuka-94a02',
    storageBucket: 'shizuka-94a02.firebasestorage.app',
    iosBundleId: 'com.moiz.shizuka.shizuka',
  );
}
